languageCode = "en-us"
title = "RC trial blog"
theme = "material"
#baseURL = "example.com"

copyright = "Â© 2018 RC"

paginate = 3
paginatePath = "page"

[languages.en]
	[[languages.en.menu.main]]
		url = "/"
		name = "Home"
		weight = 1
	[[languages.en.menu.main]]
		url = "/about"
		name = "About"
		weight = 2
